name: vultivision
description: YouTube as TV — watch your favorite channels like television.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1 # Google ile giriş desteği
  flutter_svg: ^2.0.10+1
  
  # YouTube WebView player
  webview_flutter: ^4.10.0

  # WebView Android platform
  webview_flutter_android: ^4.3.0
  
  # HTTP istekleri
  http: ^1.2.0
  
  # Güvenli API key saklama
  flutter_dotenv: ^5.1.0
  
  # Local storage (gruplar için)
  shared_preferences: ^2.3.0
  
  # İkon paketi
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - .env

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icons/icon.png"